# Generated by Django 5.2.17 on 2026-10-05 19:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.guide.models
import apps.guide.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Lokalita',
                'verbose_name_plural': 'Lokality',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255, verbose_name='Úroveň')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Číslo úrovně')),
                ('message', models.CharField(max_length=255, verbose_name='Akce')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaznamenáno')),
                ('context', models.JSONField(default=dict, verbose_name='Kontext')),
                ('extra', models.JSONField(default=dict, verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Záznam logu',
                'verbose_name_plural': 'Logy',
                'ordering': ['-logged_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('description', models.TextField(blank=True, verbose_name='Popis (HTML)')),
                ('slug', models.SlugField(help_text='Musí být unikátní a po vytvoření ho nelze změnit.', max_length=255, unique=True, verbose_name='Slug')),
                ('visible', models.BooleanField(default=True, verbose_name='Zobrazit na webu')),
                ('image', models.ImageField(blank=True, max_length=255, storage=apps.guide.storage.OverwriteStorage(), upload_to=apps.guide.models.image_upload_path, verbose_name='Obrázek')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('color', models.CharField(default='#FF9F63', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Zadejte barvu ve formátu #RRGGBB.')], verbose_name='Barva')),
                ('icon', models.CharField(blank=True, max_length=255, verbose_name='Ikona (URL)')),
            ],
            options={
                'verbose_name': 'Sekce',
                'verbose_name_plural': 'Sekce',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('description', models.TextField(blank=True, verbose_name='Popis (HTML)')),
                ('slug', models.SlugField(help_text='Musí být unikátní a po vytvoření ho nelze změnit.', max_length=255, unique=True, verbose_name='Slug')),
                ('visible', models.BooleanField(default=True, verbose_name='Zobrazit na webu')),
                ('image', models.ImageField(blank=True, max_length=255, storage=apps.guide.storage.OverwriteStorage(), upload_to=apps.guide.models.image_upload_path, verbose_name='Obrázek')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Zadejte barvu ve formátu #RRGGBB.')], verbose_name='Barva')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Odkaz na web')),
                ('map_url', models.URLField(blank=True, max_length=1000, verbose_name='URL mapy (Google Maps embed)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='guide.location', verbose_name='Lokalita')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='guide.section', verbose_name='Sekce')),
            ],
            options={
                'verbose_name': 'Téma',
                'verbose_name_plural': 'Témata',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
